# This file configures the services for your Django project on Render.
# For more details, see https://render.com/docs/yaml-spec

databases:
  - name: evoting_db
    databaseName: evoting
    user: evoting_user
    plan: free # You can upgrade this in the Render dashboard

services:
  - type: web
    name: evoting-django
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py reset_voting_data --force
      python manage.py migrate
    startCommand: "gunicorn eVoting.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: evoting_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a random secret key
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DEBUG
        value: False
      - key: WEB3_NODE_URL
        value: "YOUR_ALCHEMY_POLYGON_MAINNET_URL_HERE" # IMPORTANT: Paste your Alchemy URL here
      - key: VOTING_CONTRACT_ADDRESS
        value: "YOUR_VOTING_CONTRACT_ADDRESS_HERE"
      - key: ADMIN_CONTRACT_ADDRESS
        value: "YOUR_ADMIN_CONTRACT_ADDRESS" 