# Generated by Django 5.1.6 on 2025-03-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary')], default='President', max_length=50),
        ),
    ]
