# Generated by Django 5.1.6 on 2025-03-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
