# Generated by Django 5.1.6 on 2025-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
