# Generated by Django 4.2.20 on 2025-05-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_candidate_description_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('voter', 'Voter'), ('admin', 'Administrator')], default='voter', help_text='Designates the role or type of the user.', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Unique email address for login and communication.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed the initial OTP verification.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='Secret key for TOTP generation (auto-generated if blank).', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image for TOTP provisioning (auto-generated if blank).', null=True, upload_to='qr_codes/'),
        ),
    ]
