# Generated by Django 4.2.20 on 2025-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_customuser_user_type_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voted_candidates',
            field=models.ManyToManyField(blank=True, help_text='Candidates this user has already voted for.', related_name='voters', to='voting.candidate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address for blockchain integration.', max_length=42, null=True),
        ),
    ]
