# Generated by Django 4.2.20 on 2025-05-17 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_customuser_voted_candidates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pool Cancellation Request',
                'verbose_name_plural': 'Pool Cancellation Requests',
            },
        ),
    ]
