# Generated by Django 4.2.20 on 2025-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_poolcancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcancellationrequest',
            name='blockchain_proposal_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
