# Generated by Django 5.1.6 on 2025-06-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_cancellationrequest'),
        ('voting', '0018_poolcancellationrequest_blockchain_proposal_id'),
    ]

    operations = [
    ]
