# Generated by Django 4.2.20 on 2025-06-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_merge_20250603_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Detailed reason for admin replacement')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash if executed', max_length=66, null=True)),
                ('blockchain_proposal_id', models.BigIntegerField(blank=True, null=True)),
                ('admin_to_replace', models.ForeignKey(help_text='Admin user to be replaced', on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests_as_target', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, help_text='Admin who approved the replacement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_replacements', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(help_text='Admin who requested the replacement', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_replacements', to=settings.AUTH_USER_MODEL)),
                ('replacement_candidate', models.ForeignKey(help_text='User to become the new admin', on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests_as_candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Replacement Request',
                'verbose_name_plural': 'Admin Replacement Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
