# Generated by Django 4.2.20 on 2025-07-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_adminreplacementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pool_id',
            field=models.PositiveIntegerField(blank=True, help_text='The ID of the pool this category belongs to on the blockchain.', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'pool_id')},
        ),
    ]
