# Generated by Django 4.2.20 on 2025-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_category_pool_id_alter_candidate_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
