# Generated by Django 4.2.20 on 2025-07-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0022_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
